<?php
/**
 * 公共控制器
 * Created by PhpStorm.
 * User: liuyutao
 * Date: 2018/4/11
 * Time: 13:41
 */

namespace app\admin\controller;


use think\Controller;

class Common extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        //判断是否登录 -- 没有登录
        if (!input("?session.users")) {
            // 页面跳转
            $this->error("滚！登系统去", "login/index");
        }
        else{
            //权限判断

            //获取用户请求的控制器
            $con=$this->request->controller();
            //获取用户请求的方法
            $act=$this->request->action();
            $url=strtolower($con)."/".strtolower($act);

            //提取session里的URLArr值   权限列表的数组
            $urlArr=input("session.urlArr/a");

            if (!in_array($url,$urlArr)&&$url!="index/index"){
                $this->error("滚，你没权限");
            }



        }

    }
    public function _empty(){
        echo "<h1>505</h1>";
    }
}